---
- name: Install Jenkins and DevOps Tools directly on GCE
  hosts: jenkins_server
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install base dependencies
      apt:
        name:
          - fontconfig
          - openjdk-21-jre
          - curl
          - gnupg
          - software-properties-common
          - python3-venv
        state: present

    - name: Add deadsnakes PPA for newer Python versions
      apt_repository:
        repo: 'ppa:deadsnakes/ppa'
        state: present

    - name: Install Python 3.12 Full
      apt:
        update_cache: true
        name:
          - python3.12
          - python3.12-full
        state: present

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Install Docker Engine
      shell: curl -fsSL https://get.docker.com | sh

    - name: Add Google Cloud GPG key
      shell: |
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/google-cloud.gpg --yes

    - name: Add Google Cloud Repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/google-cloud.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
        filename: google-cloud-sdk
        state: present

    - name: Add Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins Repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        filename: jenkins
        state: present

    - name: Install Google Cloud Tools via APT
      apt:
        update_cache: true
        name:
          - jenkins
          - google-cloud-cli
          - google-cloud-cli-gke-gcloud-auth-plugin
          - kubectl
        state: present

    - name: Start and Enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Install Helm
      shell: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash

    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: true
      notify: Restart Jenkins

  handlers:
    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted